# -*- coding: utf-8 -*-
"""pokemon_svm_ver2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOsE0xJSXs8VYYrn7LDr78mBQW7LsbKH
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn import svm
import joblib  # 기계학습 후 저장하고 로드할 때 사용
from sklearn import datasets

def ai_recommend_pokemon_v2(input_attributes): #input_attributes: str
    pokemon_list = [pokemon.strip() for pokemon in input_attributes.split(',')]
    new_data = {}
    for idx, p in enumerate(pokemon_list):
        key = f"{idx + 1}위 라인업 추천 포켓몬"
        new_data[key] = p
    new_data = pd.DataFrame([new_data])

    #학습모델 불러오기
    model = joblib.load('C:/Users/NT551XCJ/Desktop/start_backend/Project/Duckemon/flaskProject/svc_model.pkl')

    # 각 열에 대해 레이블 인코더를 개별적으로 적용
    label_encoders = {}
    for column in new_data.columns:
        if new_data[column].dtype == 'object':  # 범주형 데이터만 변환
            le = LabelEncoder()
            new_data[column] = le.fit_transform(new_data[column])
            label_encoders[column] = le  # 각 열의 인코더 저장
    predictions = model.predict(new_data)

    predictions = pd.DataFrame(predictions, columns=['선택한 포켓몬'])

      # 각 열을 다시 범주형 데이터로 복구
    for column in predictions.columns:
        if column in label_encoders:
            predictions[column] = label_encoders[column].inverse_transform(predictions[column])

    # 각 열을 다시 범주형 데이터로 복구
    for column in predictions.columns:
        if column in label_encoders:
            predictions[column] = label_encoders[column].inverse_transform(predictions[column])

    recommandation = predictions['선택한 포켓몬'].values[0]
    print(f'당신의 라인업에 적당한 포켓몬은 {recommandation} 입니다.')
    return recommandation #id반환


def ai_recommend_pokemon(input_pokemons): #input_pokemons: str
    # 데이터 로드 (파일 경로를 수정하세요)
    df = pd.read_csv('C:/Users/NT551XCJ/Desktop/start_backend/Project/Duckemon/flaskProject/diss.csv')


    # 각 열에 대해 레이블 인코더를 개별적으로 적용
    label_encoders = {}
    for column in df.columns:
        if df[column].dtype == 'object':  # 범주형 데이터만 변환
            le = LabelEncoder()
            df[column] = le.fit_transform(df[column])
            label_encoders[column] = le  # 각 열의 인코더 저장

    print("숫자형 데이터로 변환된 데이터프레임:")
    print(df)

    X = df.drop('선택한 포켓몬', axis=1)
    y = df['선택한 포켓몬']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # SVM 모델 생성
    svm_model = SVC(kernel='linear', random_state=42)  # 선형 커널을 사용

    # 모델 훈련
    svm_model.fit(X_train, y_train)
    y_pred = svm_model.predict(X_test)

    # 정확도 계산
    accuracy = accuracy_score(y_test, y_pred)
    print(f'정확도: {accuracy:.2f}')

    # 분류 리포트 출력
    print("분류 리포트:")
    print(classification_report(y_test, y_pred))

    # 혼동 행렬 출력
    print("혼동 행렬:")
    print(confusion_matrix(y_test, y_pred))

    # 각 열을 다시 범주형 데이터로 복구
    for column in label_encoders:
        df[column] = label_encoders[column].inverse_transform(df[column])

    #포켓몬 대입
    pokemon_list = [pokemon.strip() for pokemon in input_pokemons.split(',')]
    new_data = {}
    for idx, p in enumerate(pokemon_list):
        key = f"{idx+1}위 라인업 추천 포켓몬"
        new_data[key] = p
    new_data = pd.DataFrame([new_data])


    for column in new_data.columns:

        if column in label_encoders:  # 첫 번째 데이터에서 인코딩한 열이 있는지 확인

            new_data[column] = label_encoders[column].transform(new_data[column])  # 인코더를 사용하여 변환

    # new_data

    model = svm.SVC()
    model.fit(X_train, y_train)

    predictions = model.predict(new_data)

    predictions = pd.DataFrame(predictions, columns=['선택한 포켓몬'])

      # 각 열을 다시 범주형 데이터로 복구
    for column in predictions.columns:
        if column in label_encoders:
            predictions[column] = label_encoders[column].inverse_transform(predictions[column])


    recommandation = predictions['선택한 포켓몬'].values[0]

    print(f'당신의 라인업에 적당한 포켓몬은 {recommandation} 입니다.')
    return recommandation #name 반환

